In [1]:
# lets now import all the required libraries
import selenium
import pandas as pd
import time
import warnings   
from bs4 import BeautifulSoup
warnings.filterwarnings("ignore")

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException

#Importing requests
import requests

# importing regex
import re

In [2]:
# Activating the chrome browser
driver = webdriver.Chrome(r"C:\Web Driver\chromedriver.exe")
time.sleep(2)

# Opening the CarDekho web url
url = "https://www.cars24.com/"
driver.get(url)
time.sleep(2)

#### Search used car on Ahmedabad location

In [3]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[8]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Ahmedabad')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[8]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

# Click on view all cars button
view_cars_btn = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[2]/div[2]/button")
view_cars_btn.click()
time.sleep(2)

In [4]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [5]:
# Display length of product url.
len(product_opening_url)

401

In [6]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,401):
    car_location.append("Ahmedabad")

In [7]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

401 401 401 401 401 401 401 401 401

In [8]:
import pandas as pd
df = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Mahindra,XUV,1.2 W6 MT,,"9,510 km",Petrol,1st Owner,2021,Ahmedabad,"₹10,67,499"
1,Maruti,Alto,VXI Manual,Manual,"8,339 km",Petrol,1st Owner,2016,Ahmedabad,"₹3,37,599"
2,Maruti,Ertiga,ZXI Plus SHVS Manual,Manual,"21,596 km",Petrol,2nd Owner,2020,Ahmedabad,"₹10,39,099"
3,Maruti,Swift,LXI Manual,Manual,"16,885 km",Petrol,1st Owner,2019,Ahmedabad,"₹5,82,299"
4,Volkswagen,Polo,Trendline 1.0 L Petrol Manual,Manual,"14,469 km",Petrol,1st Owner,2020,Ahmedabad,"₹5,82,999"
...,...,...,...,...,...,...,...,...,...,...
396,Maruti,Dzire,VXI Manual,Manual,"58,978 km",Petrol,1st Owner,2019,Ahmedabad,"₹6,19,699"
397,Maruti,Alto,LXI Manual,Manual,"56,232 km",Petrol,1st Owner,2018,Ahmedabad,"₹2,97,599"
398,Datsun,Redi,S 1.0 Manual,Manual,"27,558 km",Petrol,2nd Owner,2017,Ahmedabad,"₹2,75,599"
399,Hyundai,NEW,1.1 MAGNA CNG MT Manual,Manual,"61,631 km",Petrol + CNG,1st Owner,2021,Ahmedabad,"₹5,60,799"
400,Hyundai,Verna,1.6 SX VTVT Manual,Manual,"49,169 km",Petrol,1st Owner,2017,Ahmedabad,"₹7,94,499"

#### Search used car on Mumbai location

In [9]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Mumbai')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [10]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [11]:
# Display length of product url.
len(product_opening_url)

555

In [12]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,555):
    car_location.append("Mumbai")

In [13]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

555 555 555 555 555 555 555 555 555

In [14]:
import pandas as pd
df2 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df2

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Toyota,Fortuner,3.0 AT 4X2 Automatic,Automatic,"81,829 km",Diesel,3rd Owner,2013,Mumbai,"₹13,48,299"
1,Maruti,Ritz,ZXI Manual,Manual,"13,858 km",Petrol,1st Owner,2013,Mumbai,"₹3,77,599"
2,Toyota,Corolla,G Manual,Manual,"77,971 km",Petrol,2nd Owner,2015,Mumbai,"₹6,75,099"
3,Hyundai,Grand,SPORTS 1.2 VTVT Manual,Manual,"23,846 km",Petrol,3rd Owner,2016,Mumbai,"₹3,93,899"
4,Volkswagen,Polo,HIGHLINE1.2L PETROL Manual,Manual,"49,051 km",Petrol,2nd Owner,2013,Mumbai,"₹4,05,599"
...,...,...,...,...,...,...,...,...,...,...
550,Hyundai,i20,1.2 Manual,Manual,"47,707 km",Petrol,1st Owner,2016,Mumbai,"₹5,41,099"
551,Maruti,Wagon,LXI CNG Manual,Manual,"21,912 km",Petrol + CNG,1st Owner,2018,Mumbai,"₹4,83,499"
552,Maruti,S,ZETA 1.3 Manual,Manual,"1,21,185 km",Diesel,1st Owner,2015,Mumbai,"₹5,64,599"
553,Ford,Ecosport,1.5TITANIUM TDCI Manual,Manual,"40,270 km",Diesel,1st Owner,2018,Mumbai,"₹7,85,099"
554,Hyundai,Creta,1.6 VTVT SX AUTO Automatic,Automatic,"44,614 km",Petrol,2nd Owner,2018,Mumbai,"₹12,67,499"

#### Search used car on New Delhi location

In [15]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Delhi')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [16]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [17]:
# Display length of product url.
len(product_opening_url)

620

In [18]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,620):
    car_location.append("New Delhi")

In [19]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

620 620 620 620 620 620 620 620 620

In [20]:
import pandas as pd
df3 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df3

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Hyundai,Grand,MAGNA 1.2 KAPPA VTVT Manual,Manual,"12,782 km",Petrol,1st Owner,2018,New Delhi,"₹4,72,899"
1,KIA,SELTOS,GTX + AT PETROL Automatic,Automatic,"7,568 km",Petrol,1st Owner,2020,New Delhi,"₹17,41,799"
2,Mercedes,Benz,C 200 AVANTGARDE Automatic,Automatic,"36,806 km",Petrol,1st Owner,2014,New Delhi,"₹19,95,049"
3,MG,HECTOR,SHARP DCT,,"3,313 km",Petrol,1st Owner,2020,New Delhi,"₹18,59,999"
4,Honda,Civic,ZX CVT PETROL Automatic,Automatic,"19,005 km",Petrol,1st Owner,2019,New Delhi,"₹19,87,699"
...,...,...,...,...,...,...,...,...,...,...
615,Maruti,Vitara,VDI Manual,Manual,"79,409 km",Diesel,2nd Owner,2016,New Delhi,"₹5,72,799"
616,Hyundai,Elite,SPORTZ (O) 1.4 Manual,Manual,"73,060 km",Diesel,1st Owner,2014,New Delhi,"₹4,21,099"
617,Maruti,Swift,VDI ABS Manual,Manual,"76,094 km",Diesel,1st Owner,2015,New Delhi,"₹4,56,699"
618,Maruti,Vitara,VDI Manual,Manual,"66,181 km",Diesel,2nd Owner,2016,New Delhi,"₹5,76,599"
619,Toyota,Innova,2.5 GX 8 STR BS IV Manual,Manual,"1,19,551 km",Diesel,2nd Owner,2014,New Delhi,"₹6,71,999"

#### Search used car on Noida location

In [21]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Noida')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [22]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [23]:
# Display length of product url.
len(product_opening_url)

610

In [24]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,610):
    car_location.append("Noida")

In [25]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

610 610 610 610 610 610 610 610 610

In [26]:
import pandas as pd
df4 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df4

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Hyundai,i20,MAGNA O 1.2 Manual,Manual,"60,774 km",Petrol,1st Owner,2010,Noida,"₹2,98,999"
1,Hyundai,Grand,MAGNA 1.2 KAPPA VTVT Manual,Manual,"14,327 km",Petrol,1st Owner,2015,Noida,"₹4,04,599"
2,Maruti,Ciaz,ALPHA 1.5 AT SHVS Automatic,Automatic,"2,373 km",Petrol,1st Owner,2021,Noida,"₹11,74,899"
3,Honda,Amaze,1.2 EMT I VTEC Manual,Manual,"31,102 km",Petrol,1st Owner,2013,Noida,"₹4,18,899"
4,Hyundai,Grand,ASTA 1.2 KAPPA VTVT Manual,Manual,"14,481 km",Petrol,1st Owner,2016,Noida,"₹5,08,499"
...,...,...,...,...,...,...,...,...,...,...
605,Maruti,Swift,VDI ABS Manual,Manual,"51,483 km",Diesel,1st Owner,2015,Noida,"₹4,48,899"
606,Maruti,Vitara,VDI Manual,Manual,"66,181 km",Diesel,2nd Owner,2016,Noida,"₹5,76,599"
607,Maruti,Swift,VDI ABS Manual,Manual,"76,094 km",Diesel,1st Owner,2015,Noida,"₹4,56,699"
608,Maruti,Swift,VDI Manual,Manual,"45,699 km",Diesel,1st Owner,2013,Noida,"₹3,29,499"
609,Toyota,Innova,2.5 GX 8 STR BS IV Manual,Manual,"1,19,551 km",Diesel,2nd Owner,2014,Noida,"₹6,71,999"

#### Search used car on Gurgaon location

In [27]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Gurgaon')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [28]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,5000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [29]:
# Display length of product url.
len(product_opening_url)

607

In [30]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,607):
    car_location.append("Gurgaon")

In [31]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

607 607 607 607 607 607 607 607 607

In [32]:
import pandas as pd
df5 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df5

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,MG,HECTOR,SHARP DCT PETROL Automatic,Automatic,"8,717 km",Petrol,1st Owner,2019,Gurgaon,"₹17,90,199"
1,Honda,City,S MT PETROL Manual,Manual,"34,566 km",Petrol,1st Owner,2010,Gurgaon,"₹4,12,299"
2,MG,HECTOR,SHARP DCT PETROL Automatic,Automatic,"12,267 km",Petrol,1st Owner,2019,Gurgaon,"₹17,47,399"
3,Honda,City,S MT PETROL Manual,Manual,"39,307 km",Petrol,1st Owner,2010,Gurgaon,"₹4,13,999"
4,Jeep,Compass,2.0 LIMITED Manual,Manual,"55,376 km",Diesel,1st Owner,2018,Gurgaon,"₹12,52,199"
...,...,...,...,...,...,...,...,...,...,...
602,Maruti,Swift,VDI ABS Manual,Manual,"76,094 km",Diesel,1st Owner,2015,Gurgaon,"₹4,56,699"
603,Hyundai,Elite,SPORTZ (O) 1.4 Manual,Manual,"73,060 km",Diesel,1st Owner,2014,Gurgaon,"₹4,21,099"
604,Maruti,Alto,LXI CNG (O) Manual,Manual,"38,710 km",Petrol + CNG,1st Owner,2020,Gurgaon,"₹4,74,299"
605,Maruti,Vitara,VDI Manual,Manual,"66,181 km",Diesel,2nd Owner,2016,Gurgaon,"₹5,76,599"
606,Toyota,Innova,2.5 GX 8 STR BS IV Manual,Manual,"1,19,551 km",Diesel,2nd Owner,2014,Gurgaon,"₹6,71,999"

#### Search used car on Pune location

In [33]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Pune')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [34]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [35]:
# Display length of product url.
len(product_opening_url)

408

In [36]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,408):
    car_location.append("Pune")

In [37]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

408 408 408 408 408 408 408 408 408

In [38]:
import pandas as pd
df6 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df6

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,KIA,SELTOS,HTK PLUS 1.5 PETROL Manual,Manual,"19,355 km",Petrol,1st Owner,2020,Pune,"₹12,78,599"
1,Nissan,MAGNITE,XL Turbo CVT,,"16,049 km",Petrol,1st Owner,2021,Pune,"₹9,51,399"
2,Volkswagen,Polo,COMFORTLINE 1.0 PETROL Manual,Manual,"21,612 km",Petrol,1st Owner,2018,Pune,"₹6,09,999"
3,Toyota,URBAN,PREMIUM MT,,"1,961 km",Petrol,1st Owner,2021,Pune,"₹10,98,599"
4,Renault,Kiger,RXZ AMT 1.0 DUAL TONE,,"2,590 km",Petrol,1st Owner,2021,Pune,"₹10,61,199"
...,...,...,...,...,...,...,...,...,...,...
403,Maruti,Vitara,ZDI Manual,Manual,"28,791 km",Diesel,1st Owner,2017,Pune,"₹7,97,199"
404,Hyundai,Verna,1.6 SX VTVT Manual,Manual,"64,994 km",Petrol,1st Owner,2017,Pune,"₹7,82,299"
405,Maruti,Wagon,LXI CNG Manual,Manual,"55,622 km",Petrol + CNG,1st Owner,2018,Pune,"₹5,09,299"
406,Maruti,Vitara,ZDI Manual,Manual,"48,518 km",Diesel,1st Owner,2017,Pune,"₹7,38,199"
407,Maruti,S,DELTA 1.6 Manual,Manual,"76,022 km",Diesel,1st Owner,2016,Pune,"₹5,87,499"

#### Search used car on Bengaluru location

In [39]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Bengaluru')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [40]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [41]:
# Display length of product url.
len(product_opening_url)

390

In [42]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,390):
    car_location.append("Bengaluru")

In [43]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

390 390 390 390 390 390 390 390 390

In [44]:
import pandas as pd
df7 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df7

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,KIA,SELTOS,GTX 1.4 GDI PETROL Manual,Manual,"4,257 km",Petrol,1st Owner,2021,Bengaluru,"₹18,37,549"
1,Nissan,MAGNITE,XL Turbo CVT,,"5,523 km",Petrol,1st Owner,2021,Bengaluru,"₹9,93,099"
2,Maruti,Alto,VXI Manual,Manual,"16,710 km",Petrol,1st Owner,2010,Bengaluru,"₹2,83,099"
3,Maruti,Alto,VXI Manual,Manual,"40,125 km",Petrol,1st Owner,2014,Bengaluru,"₹3,36,499"
4,Hyundai,i10,ERA 1.1 IRDE Manual,Manual,"17,573 km",Petrol,1st Owner,2012,Bengaluru,"₹3,90,599"
...,...,...,...,...,...,...,...,...,...,...
385,Renault,Kwid,RXT 1.0 EASY-R AT Automatic,Automatic,"50,871 km",Petrol,1st Owner,2018,Bengaluru,"₹4,51,299"
386,Renault,Kwid,1.0 RXL AT Automatic,Automatic,"28,089 km",Petrol,1st Owner,2017,Bengaluru,"₹4,05,299"
387,Maruti,Baleno,DELTA 1.2 K12 AMT Automatic,Automatic,"43,004 km",Petrol,1st Owner,2017,Bengaluru,"₹6,64,699"
388,Hyundai,i20,ASTA 1.2 Manual,Manual,"33,559 km",Petrol,1st Owner,2013,Bengaluru,"₹4,80,599"
389,Honda,City,S MT PETROL Manual,Manual,"63,946 km",Petrol,2nd Owner,2011,Bengaluru,"₹4,48,399"

#### Search used car on Hyderabad location

In [45]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Hyderabad')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [46]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [47]:
# Display length of product url.
len(product_opening_url)

260

In [48]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,260):
    car_location.append("Hyderabad")

In [49]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

260 260 260 260 260 260 260 260 260

In [50]:
import pandas as pd
df8 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df8

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Hyundai,Santro,GLS Manual,Manual,"47,605 km",Petrol,1st Owner,2010,Hyderabad,"₹2,51,119"
1,Hyundai,i10,SPORTZ 1.2 Manual,Manual,"48,828 km",Petrol,1st Owner,2010,Hyderabad,"₹2,94,699"
2,Hyundai,i10,MAGNA 1.2 KAPPA2 Manual,Manual,"45,665 km",Petrol,1st Owner,2011,Hyderabad,"₹3,10,999"
3,Hyundai,i10,SPORTZ 1.2 Manual,Manual,"82,752 km",Petrol,1st Owner,2009,Hyderabad,"₹2,84,199"
4,Honda,City,S MT PETROL Manual,Manual,"70,658 km",Petrol,2nd Owner,2010,Hyderabad,"₹4,59,599"
...,...,...,...,...,...,...,...,...,...,...
255,Hyundai,Creta,S CRDI Manual,Manual,"57,451 km",Diesel,1st Owner,2020,Hyderabad,"₹14,18,599"
256,Hyundai,Verna,FLUIDIC 1.6 SX VTVT Manual,Manual,"71,379 km",Petrol,1st Owner,2017,Hyderabad,"₹7,69,899"
257,Datsun,Redi,S Manual,Manual,"34,368 km",Petrol,1st Owner,2017,Hyderabad,"₹3,12,399"
258,Maruti,Dzire,ZXI Manual,Manual,"69,711 km",Petrol,1st Owner,2019,Hyderabad,"₹7,20,299"
259,Toyota,Glanza,V CVT Automatic,Automatic,"38,612 km",Petrol,1st Owner,2020,Hyderabad,"₹8,31,599"

#### Search used car on Chennai location

In [51]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Chennai')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [52]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [53]:
# Display length of product url.
len(product_opening_url)

526

In [54]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,526):
    car_location.append("Chennai")

In [55]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

526 526 526 526 526 526 526 526 526

In [56]:
import pandas as pd
df9 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df9

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Maruti,Alto,LXI Manual,Manual,"24,280 km",Petrol,1st Owner,2015,Chennai,"₹2,67,799"
1,Maruti,Ritz,ZXI Manual,Manual,"28,929 km",Petrol,1st Owner,2014,Chennai,"₹4,23,799"
2,Maruti,Alto,LXI Manual,Manual,"22,851 km",Petrol,3rd Owner,2015,Chennai,"₹2,53,599"
3,Maruti,Swift,VXI Manual,Manual,"41,300 km",Petrol,1st Owner,2017,Chennai,"₹5,46,099"
4,Volkswagen,Vento,HIGHLINE PETROL AT Automatic,Automatic,"1,04,194 km",Petrol,2nd Owner,2011,Chennai,"₹4,02,499"
...,...,...,...,...,...,...,...,...,...,...
521,Maruti,Swift,LXI Manual,Manual,"48,553 km",Petrol,1st Owner,2018,Chennai,"₹5,46,899"
522,Maruti,Swift,VDI ABS Manual,Manual,"75,846 km",Diesel,1st Owner,2017,Chennai,"₹5,47,999"
523,Hyundai,Grand,SPORTZ 1.1 CRDI Manual,Manual,"69,608 km",Diesel,2nd Owner,2013,Chennai,"₹3,61,999"
524,Mahindra,TUV300,T8 Manual,Manual,"1,08,938 km",Diesel,1st Owner,2016,Chennai,"₹6,39,399"
525,Maruti,Swift,LXI Manual,Manual,"10,439 km",Petrol,1st Owner,2019,Chennai,"₹5,89,299"

#### Search used car on Kolkata location

In [57]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Kolkata')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/ul/li")
city_btn.click()
time.sleep(2)

In [58]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [59]:
# Display length of product url.
len(product_opening_url)

180

In [60]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,180):
    car_location.append("Kolkata")

In [61]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

180 180 180 180 180 180 180 180 180

In [62]:
import pandas as pd
df10 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df10

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Maruti,Swift,VXI Manual,Manual,"3,859 km",Petrol,1st Owner,2018,Kolkata,"₹5,37,899"
1,Maruti,Alto,LXI Manual,Manual,"5,210 km",Petrol,1st Owner,2015,Kolkata,"₹2,86,299"
2,Hyundai,VENUE,S MT 1.2 KAPPA Manual,Manual,"10,919 km",Petrol,1st Owner,2021,Kolkata,"₹7,65,299"
3,Jaguar,XF,3.0 S V6 Automatic,Automatic,"31,512 km",Diesel,1st Owner,2014,Kolkata,"₹17,14,699"
4,Hyundai,AURA,S 1.2 Kappa MT Manual,Manual,912 km,Petrol,1st Owner,2021,Kolkata,"₹6,76,299"
...,...,...,...,...,...,...,...,...,...,...
175,Maruti,S,VXI PLUS Manual,Manual,"21,973 km",Petrol,1st Owner,2019,Kolkata,"₹3,96,399"
176,Maruti,Baleno,ZETA 1.2 K12 Manual,Manual,"28,722 km",Petrol,1st Owner,2018,Kolkata,"₹6,96,099"
177,Renault,TRIBER,1.0 RXL PETROL Manual,Manual,"3,897 km",Petrol,1st Owner,2019,Kolkata,"₹6,01,699"
178,Toyota,Innova,2.5 VX 8 STR BS IV Manual,Manual,"1,55,633 km",Diesel,2nd Owner,2015,Kolkata,"₹8,57,579"
179,Hyundai,Xcent,S 1.2 Manual,Manual,"71,674 km",Petrol,1st Owner,2014,Kolkata,"₹3,25,999"

#### Search used car on Rajkot location

In [63]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Rajkot')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/div/div/ul/div/li")
city_btn.click()
time.sleep(2)

In [64]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [65]:
# Display length of product url.
len(product_opening_url)

48

In [66]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,48):
    car_location.append("Rajkot")

In [67]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

48 48 48 48 48 48 48 48 48

In [68]:
import pandas as pd
df11 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df11

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Maruti,Swift,VXI Manual,Manual,"80,582 km",Petrol,1st Owner,2016,Rajkot,"₹4,58,899"
1,Hyundai,AURA,SX+ AT 1.2CRDI Automatic,Automatic,"12,456 km",Diesel,1st Owner,2020,Rajkot,"₹9,65,199"
2,Hyundai,Elite,Magna Executive 1.2 Manual,Manual,"36,084 km",Petrol,1st Owner,2017,Rajkot,"₹5,37,999"
3,Volkswagen,Polo,HIGH LINE PLUS 1.0 Manual,Manual,"50,764 km",Petrol,1st Owner,2018,Rajkot,"₹5,54,599"
4,Maruti,Swift,VXI Manual,Manual,"51,748 km",Petrol,2nd Owner,2014,Rajkot,"₹4,23,799"
5,Hyundai,Elite,SPORTZ 1.2 Manual,Manual,"35,457 km",Petrol,2nd Owner,2018,Rajkot,"₹5,65,599"
6,Maruti,Alto,LXI Manual,Manual,"75,671 km",Petrol,1st Owner,2017,Rajkot,"₹2,91,799"
7,Hyundai,NEW,SPORTZ 1.1 Manual,Manual,"5,048 km",Petrol,1st Owner,2020,Rajkot,"₹5,15,799"
8,Maruti,Baleno,DELTA 1.2 K12 Manual,Manual,"41,690 km",Petrol,2nd Owner,2017,Rajkot,"₹5,07,699"
9,Maruti,Ciaz,VXI PLUS Manual,Manual,"48,280 km",Petrol,1st Owner,2016,Rajkot,"₹6,07,199"
10,Maruti,IGNIS,SIGMA 1.2 K12 Manual,Manual,"13,673 km",Petrol,1st Owner,2020,Rajkot,"₹4,80,499"
11,Maruti,Alto,LXI Manual,Manual,"70,300 km",Petrol,1st Owner,2018,Rajkot,"₹2,87,499"
12,Maruti,Baleno,DELTA DDIS 190 Manual,Manual,"73,094 km",Diesel,2nd Owner,2017,Rajkot,"₹4,99,599"
13,Maruti,Wagon,LXI Manual,Manual,"29,119 km",Petrol,1st Owner,2017,Rajkot,"₹3,91,999"
14,Maruti,Alto,LXI Manual,Manual,"97,455 km",Petrol,1st Owner,2018,Rajkot,"₹2,89,499"
15,Maruti,Baleno,ZETA 1.2 K12 Manual,Manual,"70,059 km",Petrol,1st Owner,2019,Rajkot,"₹5,78,599"
16,Maruti,Alto,LXI Manual,Manual,"12,020 km",Petrol,2nd Owner,2018,Rajkot,"₹3,18,999"
17,Maruti,Alto,LXI Manual,Manual,"12,094 km",Petrol,1st Owner,2020,Rajkot,"₹3,63,399"
18,Maruti,Vitara,ZDI PLUS DUAL TONE Manual,Manual,"1,50,257 km",Diesel,2nd Owner,2016,Rajkot,"₹6,70,199"
19,Hyundai,Grand,MAGNA 1.2 VTVT Manual,Manual,"1,00,616 km",Petrol,1st Owner,2015,Rajkot,"₹3,88,199"
20,Honda,Jazz,1.2 V MT Manual,Manual,"30,781 km",Petrol,2nd Owner,2018,Rajkot,"₹5,46,599"
21,Honda,City,VX CVT PETROL Automatic,Automatic,"94,609 km",Petrol,1st Owner,2018,Rajkot,"₹8,42,399"
22,Hyundai,i10,MAGNA 1.1 IRDE2 Manual,Manual,"41,268 km",Petrol,1st Owner,2015,Rajkot,"₹3,48,499"
23,Maruti,Wagon,VXI Manual,Manual,"98,828 km",Petrol,1st Owner,2014,Rajkot,"₹3,22,999"
24,Maruti,Baleno,DELTA 1.2 K12 Manual,Manual,"19,376 km",Petrol,1st Owner,2019,Rajkot,"₹6,19,299"
25,Maruti,Alto,LXI Manual,Manual,"66,206 km",Petrol,1st Owner,2017,Rajkot,"₹2,73,699"
26,Maruti,Alto,LXI Manual,Manual,"17,778 km",Petrol,1st Owner,2019,Rajkot,"₹3,25,299"
27,Maruti,IGNIS,SIGMA 1.2 K12 Manual,Manual,"38,813 km",Petrol,1st Owner,2020,Rajkot,"₹4,76,299"
28,Maruti,Wagon,VXI Manual,Manual,"60,044 km",Petrol,1st Owner,2017,Rajkot,"₹3,98,499"
29,Maruti,Dzire,VXI Manual,Manual,"51,930 km",Petrol,1st Owner,2019,Rajkot,"₹6,33,299"
30,Maruti,Wagon,VXI Manual,Manual,"71,567 km",Petrol,1st Owner,2013,Rajkot,"₹3,16,599"
31,Maruti,Alto,VXI (O) AMT Automatic,Automatic,"70,918 km",Petrol,1st Owner,2017,Rajkot,"₹3,23,499"
32,Hyundai,Grand,MAGNA 1.2 KAPPA VTVT Manual,Manual,"70,184 km",Petrol,1st Owner,2017,Rajkot,"₹4,75,999"
33,Maruti,Alto,LXI Manual,Manual,"67,373 km",Petrol,1st Owner,2017,Rajkot,"₹2,91,299"
34,Maruti,S,ZETA 1.3 SHVS Manual,Manual,"76,025 km",Diesel,1st Owner,2018,Rajkot,"₹7,99,099"
35,Maruti,Alto,LXI Manual,Manual,"38,743 km",Petrol,1st Owner,2020,Rajkot,"₹3,34,099"
36,Maruti,Alto,LXI Manual,Manual,"43,186 km",Petrol,1st Owner,2018,Rajkot,"₹3,17,699"
37,Maruti,Alto,LXI Manual,Manual,"8,556 km",Petrol,1st Owner,2019,Rajkot,"₹3,44,999"
38,Maruti,Alto,VXI Manual,Manual,"32,779 km",Petrol,1st Owner,2020,Rajkot,"₹3,88,499"
39,Maruti,Alto,LXI Manual,Manual,"21,785 km",Petrol,1st Owner,2021,Rajkot,"₹3,82,199"
40,Maruti,Alto,LXI Manual,Manual,"20,662 km",Petrol,1st Owner,2020,Rajkot,"₹3,42,199"
41,Maruti,Alto,LXI Manual,Manual,"25,290 km",Petrol,1st Owner,2018,Rajkot,"₹3,15,299"
42,Maruti,Alto,LXI Manual,Manual,"21,722 km",Petrol,1st Owner,2019,Rajkot,"₹3,35,019"
43,Maruti,Swift,VXI Manual,Manual,"90,593 km",Petrol,1st Owner,2019,Rajkot,"₹5,61,599"
44,Maruti,Baleno,DELTA 1.2 K12 Manual,Manual,"27,160 km",Petrol,1st Owner,2019,Rajkot,"₹6,27,299"
45,Hyundai,Grand,MAGNA 1.2 KAPPA VTVT Manual,Manual,"88,370 km",Petrol,1st Owner,2016,Rajkot,"₹4,27,499"
46,Hyundai,Elite,ASTA 1.2 (O) Manual,Manual,"45,979 km",Petrol,1st Owner,2017,Rajkot,"₹6,32,199"
47,Maruti,Vitara,ZDI Manual,Manual,"67,447 km",Diesel,1st Owner,2018,Rajkot,"₹7,62,599"

#### Search used car on Lucknow location

In [69]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Lucknow')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/div/div/ul/div/li")
city_btn.click()
time.sleep(2)

In [70]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [71]:
# Display length of product url.
len(product_opening_url)

145

In [72]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,145):
    car_location.append("Lucknow")

In [73]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

145 145 145 145 145 145 145 145 145

In [74]:
import pandas as pd
df12 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df12

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Hyundai,Grand,SPORTZ 1.2 KAPPA VTVT Manual,Manual,"34,105 km",Petrol,1st Owner,2017,Lucknow,"₹4,42,999"
1,Ford,Ecosport,1.5 TREND+ TDCI Manual,Manual,"61,140 km",Diesel,1st Owner,2017,Lucknow,"₹6,04,499"
2,Ford,Ecosport,1.5TITANIUM TDCI Manual,Manual,"41,151 km",Diesel,1st Owner,2016,Lucknow,"₹7,10,899"
3,Maruti,Swift,VXI Manual,Manual,"25,331 km",Petrol,1st Owner,2021,Lucknow,"₹6,95,899"
4,KIA,SONET,HTK+ 1.5 D AT,,"13,887 km",Diesel,1st Owner,2021,Lucknow,"₹11,07,299"
...,...,...,...,...,...,...,...,...,...,...
140,Hyundai,NEW,SPORTZ 1.1 Manual,Manual,"38,030 km",Petrol + CNG,1st Owner,2018,Lucknow,"₹5,06,499"
141,Maruti,Dzire,VXI Manual,Manual,"53,665 km",Petrol,1st Owner,2018,Lucknow,"₹6,40,299"
142,Maruti,Dzire,VXI Manual,Manual,"34,337 km",Petrol,1st Owner,2019,Lucknow,"₹6,87,599"
143,Renault,TRIBER,RXZ AT Automatic,Automatic,"12,943 km",Petrol,1st Owner,2020,Lucknow,"₹6,32,799"
144,Maruti,Wagon,VXI AMT Automatic,Automatic,"45,793 km",Petrol,2nd Owner,2016,Lucknow,"₹3,88,799"

#### Search used car on Jaipur location

In [75]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Jaipur')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/div/div/ul/div/li")
city_btn.click()
time.sleep(2)

In [76]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [77]:
# Display length of product url.
len(product_opening_url)

141

In [78]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,141):
    car_location.append("Jaipur")

In [79]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

141 141 141 141 141 141 141 141 141

In [80]:
import pandas as pd
df13 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df13

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Maruti,Baleno,SIGMA 1.2 K12 Manual,Manual,"61,106 km",Petrol,3rd Owner,2016,Jaipur,"₹4,71,899"
1,Hyundai,Grand,SPORTS 1.2 VTVT Manual,Manual,"78,383 km",Petrol,2nd Owner,2017,Jaipur,"₹4,54,199"
2,Hyundai,Creta,1.6 SX (O) CRDI Manual,Manual,"32,640 km",Diesel,2nd Owner,2016,Jaipur,"₹10,58,999"
3,Renault,Kwid,1.0 RXT Opt Manual,Manual,"98,340 km",Petrol,2nd Owner,2017,Jaipur,"₹2,85,899"
4,Maruti,Swift,VXI Manual,Manual,"16,007 km",Petrol,1st Owner,2021,Jaipur,"₹7,24,699"
...,...,...,...,...,...,...,...,...,...,...
136,Maruti,Dzire,VDI Manual,Manual,"63,733 km",Diesel,1st Owner,2018,Jaipur,"₹6,91,399"
137,Maruti,Dzire,VDI Manual,Manual,"1,40,890 km",Diesel,1st Owner,2018,Jaipur,"₹6,85,499"
138,Maruti,Alto,VXI AMT Automatic,Automatic,"54,752 km",Petrol,1st Owner,2016,Jaipur,"₹3,29,599"
139,Maruti,Dzire,VXI Manual,Manual,"52,017 km",Petrol,1st Owner,2018,Jaipur,"₹6,54,599"
140,Maruti,Alto,VXI (O) AMT Automatic,Automatic,"30,406 km",Petrol,1st Owner,2018,Jaipur,"₹3,87,799"

#### Search used car on Kochi location

In [81]:
# Click on expand btn for list of cities.
expand_other_locations = driver.find_element_by_xpath("/html/body/div[1]/div[1]/header/div/div[1]/div[2]/p/img")
expand_other_locations.click()
time.sleep(2)

# Then click the search bar and enter city name.
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[1]/div/div[2]/div/input")
search_bar.send_keys('Kochi')
time.sleep(2)

# Click searched city button.
city_btn = driver.find_element_by_xpath("/html/body/div[1]/div[6]/div/div/div/div/div[2]/div/div/ul/div/li")
city_btn.click()
time.sleep(2)

In [82]:
# Fetching url to open each product
for _ in range(20):
    driver.execute_script("window.scrollBy(0,7000)")
    time.sleep(2)
    
product_opening_url = []
url = driver.find_elements_by_xpath('//a[@class="_9Ue0B"]')

for i in url:
        try:
            product_opening_url.append(i.get_attribute('href'))
        except NoSuchElementException:
            product_opening_url.append('-')

In [83]:
# Display length of product url.
len(product_opening_url)

306

In [84]:
# So lets extract all the tags having the product brand name

#scarping brand name
car_brand_name = []
try:                    
    car_brand_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_brand_tags:
        car_brand_name.append(i.text.split(" ")[1])
except NoSuchElementException:#handling no such element exception
    car_brand_name.append('No details available')

#scarping model name
car_model_name = []
try:                    
    car_model_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_model_tags:
        car_model_name.append(i.text.split(" ")[2])
except NoSuchElementException:#handling no such element exception
    car_model_name.append('No details available')
    
#scarping car variant
car_variant = []
try:                    
    car_variant_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p")
    for i in car_variant_tags:
        car_variant.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_variant.append('No details available')
    
#scarping car transmission
car_transmission = []
try:                    
    car_transmission_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/p/span")
    for i in car_transmission_tags:
        car_transmission.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_transmission.append('No details available')
    
#scarping car driven km
car_driven_km = []
try:                    
    car_driven_km_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[1]")
    for i in car_driven_km_tags:
        car_driven_km.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_driven_km.append('No details available')
    
#scarping car owners
car_owners = []
try:                    
    car_owners_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[2]")
    for i in car_owners_tags:
        car_owners.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_owners.append('No details available')
    
#scarping car fuel
car_fuel = []
try:                    
    car_fuel_tags=driver.find_elements_by_xpath("//ul[@class='bVR0c']/li[3]")
    for i in car_fuel_tags:
        car_fuel.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_fuel.append('No details available')
    
#scarping car price
car_price = []
try:                    
    car_price_tags=driver.find_elements_by_xpath("//div[@class='_7udZZ']/span")
    for i in car_price_tags:
        car_price.append(i.text)
except NoSuchElementException:#handling no such element exception
    car_price.append('No details available')
    
#scraping car manu.year
car_manuf_year = []
try:                    
    car_manuf_year_tags=driver.find_elements_by_xpath("//div[@class='_1jpRU']/h2")
    for i in car_manuf_year_tags:
        car_manuf_year.append(i.text.split(" ")[0])
except NoSuchElementException:#handling no such element exception
    car_manuf_year.append('No details available')
    
#scraping car location
car_location = []
for _ in range(0,306):
    car_location.append("Kochi")

In [85]:
print(len(car_brand_name),len(car_model_name),len(car_variant),len(car_driven_km),len(car_fuel),len(car_owners),len(car_transmission),len(car_manuf_year),len(car_location))

306 306 306 306 306 306 306 306 306

In [86]:
import pandas as pd
df14 = pd.DataFrame({
    "Brand":car_brand_name,
    "Model":car_model_name,
    "Variant":car_variant,
    "Transmission":car_transmission,
    "Driven_KM":car_driven_km,
    "Fuel_type":car_fuel,
    "No. of owners":car_owners,
    "Manufacture_year":car_manuf_year,
    "Location":car_location,
    "Price":car_price
})
df14

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Hyundai,i10,SPORTZ 1.2 Manual,Manual,"23,729 km",Petrol,2nd Owner,2008,Kochi,"₹2,26,999"
1,Hyundai,i10,SPORTZ 1.2 KAPPA2 Manual,Manual,"42,652 km",Petrol,3rd Owner,2011,Kochi,"₹2,74,399"
2,Hyundai,Santro,GLS Manual,Manual,"64,920 km",Petrol,1st Owner,2011,Kochi,"₹1,94,199"
3,Maruti,Wagon,LXI Manual,Manual,"56,465 km",Petrol,1st Owner,2008,Kochi,"₹1,83,799"
4,Hyundai,Elite,SPORTZ 1.2 Manual,Manual,"18,361 km",Petrol,1st Owner,2016,Kochi,"₹5,69,499"
...,...,...,...,...,...,...,...,...,...,...
301,Maruti,Alto,LXI Manual,Manual,"51,233 km",Petrol,1st Owner,2019,Kochi,"₹3,16,399"
302,Maruti,Alto,VXI Manual,Manual,"76,693 km",Petrol,1st Owner,2015,Kochi,"₹2,56,899"
303,Maruti,Eeco,5 STR WITH AC PLUSHTR Manual,Manual,"14,835 km",Petrol,1st Owner,2020,Kochi,"₹4,43,999"
304,Hyundai,Grand,SPORTZ (O) 1.2 AT VTVT Automatic,Automatic,"23,695 km",Petrol,2nd Owner,2017,Kochi,"₹5,26,719"
305,Hyundai,Creta,1.6 SX CRDI Manual,Manual,"54,729 km",Diesel,1st Owner,2018,Kochi,"₹10,93,999"

In [87]:
df_final = pd.concat([df,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12,df13,df14],axis=0,ignore_index=True)
df_final

,Brand,Model,Variant,Transmission,Driven_KM,Fuel_type,No. of owners,Manufacture_year,Location,Price
0,Mahindra,XUV,1.2 W6 MT,,"9,510 km",Petrol,1st Owner,2021,Ahmedabad,"₹10,67,499"
1,Maruti,Alto,VXI Manual,Manual,"8,339 km",Petrol,1st Owner,2016,Ahmedabad,"₹3,37,599"
2,Maruti,Ertiga,ZXI Plus SHVS Manual,Manual,"21,596 km",Petrol,2nd Owner,2020,Ahmedabad,"₹10,39,099"
3,Maruti,Swift,LXI Manual,Manual,"16,885 km",Petrol,1st Owner,2019,Ahmedabad,"₹5,82,299"
4,Volkswagen,Polo,Trendline 1.0 L Petrol Manual,Manual,"14,469 km",Petrol,1st Owner,2020,Ahmedabad,"₹5,82,999"
...,...,...,...,...,...,...,...,...,...,...
5192,Maruti,Alto,LXI Manual,Manual,"51,233 km",Petrol,1st Owner,2019,Kochi,"₹3,16,399"
5193,Maruti,Alto,VXI Manual,Manual,"76,693 km",Petrol,1st Owner,2015,Kochi,"₹2,56,899"
5194,Maruti,Eeco,5 STR WITH AC PLUSHTR Manual,Manual,"14,835 km",Petrol,1st Owner,2020,Kochi,"₹4,43,999"
5195,Hyundai,Grand,SPORTZ (O) 1.2 AT VTVT Automatic,Automatic,"23,695 km",Petrol,2nd Owner,2017,Kochi,"₹5,26,719"
5196,Hyundai,Creta,1.6 SX CRDI Manual,Manual,"54,729 km",Diesel,1st Owner,2018,Kochi,"₹10,93,999"

In [88]:
 df_final.to_excel(r'car_data.xlsx',index=False)