# Web Scraping Assignment_4

In [1]:
# lets now import all the required libraries
import selenium
import pandas as pd
import time
import warnings   
from bs4 import BeautifulSoup
warnings.filterwarnings("ignore")

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException,ElementNotInteractableException

#Importing requests
import requests

# importing regex
import re

Q.1 - Scrape the details of most viewed videos on YouTube from Wikipedia.Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details: (A) Rank (B) Name (C) Artist (D) Upload date (E) Views

In [3]:
# Activating the chrome browser
driver = webdriver.Chrome('chromedriver.exe')
time.sleep(2)

# Opening the wikipedia
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver.get(url)

time.sleep(2)

# Scraping rank of the video
rank = []
try:
    ranks = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[1]')
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:#handling no such element exception
    rank.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    rank.append('No details available')
    
time.sleep(2)

# Scraping name of the video
name = []
try:
    names = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[2]')
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    name.append('No details available')
    
time.sleep(2)

# Scraping artist of the video
artist = []
try:
    artists = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[3]')
    for i in artists:
        artist.append(i.text)
except NoSuchElementException:#handling no such element exception
    artist.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    artist.append('No details available')

time.sleep(2)

# Scraping view of the video
view = []
try:
    views = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[4]')
    for i in artists:
        view.append(i.text)
except NoSuchElementException:#handling no such element exception
    view.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    view.append('No details available')

time.sleep(2)

# Scraping upload date of the video
upload_date = []
try:
    upload_dates = driver.find_elements_by_xpath('//table[@class="wikitable sortable jquery-tablesorter"][1]/tbody/tr/td[5]')
    for i in upload_dates:
        upload_date.append(i.text)
except NoSuchElementException:#handling no such element exception
    upload_date.append('No details available')
except StaleElementReferenceException:#handling Stale element exception
    upload_date.append('No details available')

time.sleep(2)

# Finally create a dataframe of the scraped data.
df=pd.DataFrame({"Rank":rank,
                 "Name":name,
                 "artist":artist,
                 "Views(in billion)":views,
                 "Date of upload":upload_date
                })
df

,Rank,Name,artist,Views(in billion),Date of upload
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,<selenium.webdriver.remote.webelement.WebEleme...,"June 17, 2016"
1,2.,"""Despacito""[6]",Luis Fonsi,<selenium.webdriver.remote.webelement.WebEleme...,"January 12, 2017"
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,<selenium.webdriver.remote.webelement.WebEleme...,"October 8, 2016"
3,4.,"""Shape of You""[13]",Ed Sheeran,<selenium.webdriver.remote.webelement.WebEleme...,"January 30, 2017"
4,5.,"""See You Again""[15]",Wiz Khalifa,<selenium.webdriver.remote.webelement.WebEleme...,"April 6, 2015"
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,<selenium.webdriver.remote.webelement.WebEleme...,"May 2, 2018"
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,<selenium.webdriver.remote.webelement.WebEleme...,"March 6, 2014"
7,8.,"""Uptown Funk""[22]",Mark Ronson,<selenium.webdriver.remote.webelement.WebEleme...,"November 19, 2014"
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,<selenium.webdriver.remote.webelement.WebEleme...,"February 27, 2018"
9,10.,"""Masha and the Bear – Recipe for Disaster""[24]",Get Movies,<selenium.webdriver.remote.webelement.WebEleme...,"January 31, 2012"
10,11.,"""Gangnam Style""[25]",Psy,<selenium.webdriver.remote.webelement.WebEleme...,"July 15, 2012"
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,<selenium.webdriver.remote.webelement.WebEleme...,"May 24, 2018"
12,13.,"""Dame Tu Cosita""[31]",El Chombo,<selenium.webdriver.remote.webelement.WebEleme...,"April 5, 2018"
13,14.,"""Sugar""[32]",Maroon 5,<selenium.webdriver.remote.webelement.WebEleme...,"January 14, 2015"
14,15.,"""Roar""[33]",Katy Perry,<selenium.webdriver.remote.webelement.WebEleme...,"September 5, 2013"
15,16.,"""Counting Stars""[34]",OneRepublic,<selenium.webdriver.remote.webelement.WebEleme...,"May 31, 2013"
16,17.,"""Sorry""[35]",Justin Bieber,<selenium.webdriver.remote.webelement.WebEleme...,"October 22, 2015"
17,18.,"""Thinking Out Loud""[36]",Ed Sheeran,<selenium.webdriver.remote.webelement.WebEleme...,"October 7, 2014"
18,19.,"""Axel F""[37]",Crazy Frog,<selenium.webdriver.remote.webelement.WebEleme...,"June 16, 2009"
19,20.,"""Girls Like You""[38]",Maroon 5,<selenium.webdriver.remote.webelement.WebEleme...,"May 31, 2018"
20,21.,"""Faded""[39]",Alan Walker,<selenium.webdriver.remote.webelement.WebEleme...,"December 3, 2015"
21,22.,"""Dark Horse""[40]",Katy Perry,<selenium.webdriver.remote.webelement.WebEleme...,"February 20, 2014"
22,23.,"""Baa Baa Black Sheep""[41]",Cocomelon – Nursery Rhymes,<selenium.webdriver.remote.webelement.WebEleme...,"June 25, 2018"
23,24.,"""Let Her Go""[42]",Passenger,<selenium.webdriver.remote.webelement.WebEleme...,"July 25, 2012"
24,25.,"""Bailando""[43]",Enrique Iglesias,<selenium.webdriver.remote.webelement.WebEleme...,"April 11, 2014"
25,26.,"""Lean On""[44]",Major Lazer,<selenium.webdriver.remote.webelement.WebEleme...,"March 22, 2015"
26,27.,"""Perfect""[45]",Ed Sheeran,<selenium.webdriver.remote.webelement.WebEleme...,"November 9, 2017"
27,28.,"""Shake It Off""[46]",Taylor Swift,<selenium.webdriver.remote.webelement.WebEleme...,"August 18, 2014"
28,29.,"""Waka Waka (This Time for Africa)""[47]",Shakira,<selenium.webdriver.remote.webelement.WebEleme...,"June 4, 2010"
29,30.,"""Mi Gente""[48]",J Balvin,<selenium.webdriver.remote.webelement.WebEleme...,"June 29, 2017"

Q.2 - Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [18]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 

time.sleep(2)

# Opening the bcci.tv
url = "https://www.bcci.tv/"
driver.get(url)

time.sleep(2)

In [19]:
#going to international fixtures page
fixtures=driver.find_element_by_xpath("//div[@class='collapse navbar-collapse']/ul[1]/li[2]/a")
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    
time.sleep(2)

In [20]:
# make empty lists
match=[] 
series=[]
place=[]
date=[]
Time=[]

In [21]:
#scraping time
time_title=driver.find_elements_by_xpath("//h5[@class='text-right ng-binding']")
for i in time_title:
    if i.text is None :
        Time.append("--") 
    else:
        Time.append(i.text)

In [22]:
# scrape match details urls from xpath    
urls=[]
match_page=driver.find_elements_by_xpath("//a[@class='match-center-btn ng-scope']")  
for i in match_page:
    urls.append(i.get_attribute('href'))

time.sleep(2)

for i in urls:                 #list of urls of match description pages
    driver.get(i)
    
    time.sleep(2)
    
    #scarping match title
    try:                    
        match_title=driver.find_element_by_xpath("//div[@class='widget matchDetails hideMobOnly showForSpecialCase']/div/ul/li[2]/span[2]")
        match.append(match_title.text)
    except NoSuchElementException:#handling no such element exception
        match.append('No details available')
    
    time.sleep(2)
    #scarping series title    
    try:
        series_title=driver.find_element_by_xpath("//div[@class='widget matchDetails hideMobOnly showForSpecialCase']/div/ul/li[1]/span[2]")
        series.append(series_title.text)
    except NoSuchElementException:#handling no such element exception
        series.append("No details Available")
    
    time.sleep(2)
    
    #scarping date of match 
    try:
        date_title=driver.find_element_by_xpath("//div[@class='matchDate alignC ng-binding ng-scope']")
        date.append(date_title.text)
    except NoSuchElementException:#handling no such element exception
        date.append("No details Available")      
    
    time.sleep(2)
    
     #scarping match venue    
    try:
        place_title=driver.find_element_by_xpath("//div[@class='widget matchDetails hideMobOnly showForSpecialCase']/div/ul/li[3]/span[2]")
        place.append(place_title.text)
    except NoSuchElementException:#handling no such element exception
        place.append("No details Available")
        

#preparing the dataframe
df=pd.DataFrame({"Match":match,
                "Series":series,
                "Place":place,
                "Date":date,
                "Time":Time})
df

,Match,Series,Place,Date,Time
0,Sri Lanka Women VS India Women,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,RANGIRI DAMBULLA INTERNATIONAL STADIUM,23 JUN 2022,2:30 PM IST
1,Sri Lanka Women VS India Women,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,RANGIRI DAMBULLA INTERNATIONAL STADIUM,25 JUN 2022,2:30 PM IST
2,Ireland VS India,INDIA TOUR OF IRELAND T20 SERIES 2022,THE VILLAGE,26 JUN 2022,9:00 PM IST
3,Sri Lanka Women VS India Women,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,RANGIRI DAMBULLA INTERNATIONAL STADIUM,27 JUN 2022,2:30 PM IST
4,Ireland VS India,INDIA TOUR OF IRELAND T20 SERIES 2022,THE VILLAGE,28 JUN 2022,9:00 PM IST
5,Sri Lanka Women VS India Women,INDIA WOMEN TOUR OF SRI LANKA ODI SERIES 2022,PALLEKELE INTERNATIONAL CRICKET STADIUM,1 JUL 2022,10:00 AM IST
6,England VS India,INDIA TOUR OF ENGLAND TEST SERIES 2021,EDGBASTON,1 JUL 2022,3:30 PM IST
7,Sri Lanka Women VS India Women,INDIA WOMEN TOUR OF SRI LANKA ODI SERIES 2022,PALLEKELE INTERNATIONAL CRICKET STADIUM,4 JUL 2022,10:00 AM IST

Q3. - Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [23]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the guru99.com
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)

In [24]:
#clicking on selenium option under testing menu open its tutorial
selenium_link = driver.find_element_by_xpath("//div[@class='featured-box cloumnsize1']/ul[1]/li[3]/a")
try:
    selenium_link.click()
except ElementNotInteractableException:          #handling element not clickable exception
    driver.get(selenium_link.get_attribute('href'))
time.sleep(2)

In [25]:
#clicking on Selenium Exception Handling (Common Exceptions List) under Advance Webdriver Stuff!
exception_handle_link=driver.find_element_by_xpath("//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handle_link.click()
except ElementNotInteractableException:      #handling element not clickable exception
    driver.get(exception_handle_link.get_attribute('href'))              
time.sleep(2)

In [27]:
#scraping exceptions names
name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:      #handling no such element exception
    name.append('No details available')
time.sleep(2)   

#scraping exceptions description
desc=[]
try:
    desc_list=driver.find_elements_by_xpath("//table[@class='table table-striped']/tbody/tr/td[2]")
    for i in desc_list:
        desc.append(i.text)
except NoSuchElementException:#handling no such element exception
    desc.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Exception_name":name,
                "Description":desc})
df

,Exception_name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

Q4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [41]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the statisticstimes.com
url = "http://statisticstimes.com/"
driver.get(url)
time.sleep(2)

In [42]:
#clicking on economy button
economy=driver.find_element_by_xpath("//div[@class='dropdown'][2]/div/a[3]")
try:
    economy.click()
except ElementNotInteractableException:
    driver.get(economy.get_attribute('href'))
time.sleep(2)

In [43]:
#clicking on gdp of indian states
indian_states=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")

try:
    indian_states.click()
except ElementNotInteractableException:
    driver.get(indian_states.get_attribute('href')) 
time.sleep(2)

In [45]:
#scraping rank
rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[1]")
    for i in ranks:
        rank.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    rank.append('No details available')
time.sleep(2)


#scraping States
State=[]
try:
    states=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[2]")
    for i in states:
        State.append(i.text)
except NoSuchElementException:                 #handling no such element exception
    State.append('No details available')
time.sleep(2)


#scraping GSDP(19-20)
GSDP_20=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[3]")
    for i in info:
        GSDP_20.append(i.text)
except NoSuchElementException:           #handling no such element exception
    GSDP_20.append('No details available')
time.sleep(2)    
    
#scraping GSDP(18-19)
GSDP_19=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[4]")
    for i in info:
        GSDP_19.append(i.text)
except NoSuchElementException:        #handling no such element exception
    GSDP_19.append('No details available')
time.sleep(2)

#scraping share (18-19)
share=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[5]")
    for i in info:
        share.append(i.text)
except NoSuchElementException:          #handling no such element exception
    share.append('No details available')
time.sleep(2)

#scraping GDP(billion$)
GDP_billion=[]
try:
    info=driver.find_elements_by_xpath("//div[@id='table_id_wrapper']/table/tbody/tr/td[6]")
    for i in info:
        GDP_billion.append(i.text)
except NoSuchElementException:            #handling no such element exception
    GDP_billion.append('No details available')
time.sleep(2)

#creatng dataframe
df=pd.DataFrame({'Rank':rank,
                'State':State,
                'GSDP(19-20)':GSDP_20,
                'GSDP(18-19)':GSDP_19,
                'Share(18-19)':share,
                'GDP(Billion_$)':GDP_billion})
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP(Billion_$)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

Q5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [30]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the github
url = "https://github.com/"
driver.get(url)

In [31]:
# clicking on explore option button
explore=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
explore.click()
time.sleep(2)

#then finding trending option and click
trending=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
try:
    trending.click()
except:
    driver.get(trending.get_attribute('href'))
time.sleep(2)

In [32]:
# making empty lists    
repo_urls=[]
repo_title=[]
repo_desc=[]
contributors_count=[]
language_used=[]

#scraping repositories urls
repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2)

#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)

for i in repo_urls:
    driver.get(i)
    time.sleep(3)
    
    #scraping repositories discription
    try:          
        repo_desc.append(driver.find_element_by_xpath("//p[@class='f4 my-3']").text)
    except:
        repo_desc.append('-')
        
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("/html/body/div[4]/div/main/div[2]/div/div/div[3]/div[2]/div/div[6]/div/h2/a/span")
        contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        contributors_count.append('No details available')
    time.sleep(2)
    
    #scraping languages used
    language_list=[]
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']/a/span[1]")
    if languages:    
        for i in languages:
            language_list.append(i.text)
    else:
        language_list.append('No languages used')
    language_used.append(language_list)

time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':contributors_count,
                'Language_used':language_used})
df

,Title,Description,Contributors_count,Language_used
0,kraanzu / dooit,A TUI todo manager,No details available,[Python]
1,girliemac / a-picture-is-worth-a-1000-words,I am trying to describe complex matters in sim...,No details available,[No languages used]
2,alibaba / IOC-golang,一款服务于 Go 开发者的依赖注入框架，方便搭建任何 Go 应用。 A Golang dep...,No details available,[Go]
3,ToolJet / ToolJet,Extensible low-code framework for building bus...,No details available,"[JavaScript, TypeScript, SCSS, Shell, EJS, Doc..."
4,jfecher / ante,"A safe, easy systems language",No details available,"[Rust, Scala]"
5,LunarVim / nvim-basic-ide,This is my attempt at a basic stable starting ...,No details available,[Lua]
6,NomicFoundation / hardhat,Hardhat is a development environment to compil...,No details available,"[TypeScript, Solidity, JavaScript]"
7,daffainfo / AllAboutBugBounty,"All about bug bounty (bypasses, payloads, and ...",No details available,[No languages used]
8,spacedriveapp / spacedrive,Spacedrive is an open source cross-platform fi...,No details available,"[TypeScript, Rust, CSS, JavaScript, Swift, SCSS]"
9,dblalock / bolt,10x faster matrix and vector operations,No details available,"[C++, Python, C, Jupyter Notebook, SWIG, CMake]"
10,tauri-apps / tauri,"Build smaller, faster, and more secure desktop...",172,"[Rust, TypeScript, JavaScript, Shell, PowerShe..."
11,wdzeng / shopee-coins-bot,💰💰 蝦皮簽到機器人 💰💰,No details available,"[TypeScript, Dockerfile]"
12,Asabeneh / 30-Days-Of-JavaScript,30 days of JavaScript programming challenge is...,No details available,"[JavaScript, HTML]"
13,InterviewReady / system-design-resources,These are the best resources for System Design...,No details available,[No languages used]
14,elebumm / RedditVideoMakerBot,Create Reddit Videos with just✨ one command ✨,No details available,"[Python, PowerShell]"
15,Elfocrash / .NET-Backend-Developer-Roadmap,Nick's Roadmap for a .NET Backend Developer wo...,No details available,[No languages used]
16,TGX-Android / Telegram-X,The main repository of Telegram X — official a...,No details available,"[Java, Kotlin]"
17,Q930844N / awesome_tech_content,Technology related content shared by folks on ...,No details available,[No languages used]
18,dragonflydb / dragonfly,A modern replacement for Redis and Memcached,No details available,"[C++, C]"
19,Lightning-AI / lightning,Build high-performance AI models with PyTorch ...,No details available,"[Python, Dockerfile, TypeScript, Shell, HTML, ..."
20,onevcat / Kingfisher,"A lightweight, pure-Swift library for download...",170,"[Swift, Objective-C, Ruby]"
21,Alamofire / Alamofire,Elegant HTTP Networking in Swift,240,[Swift]
22,alecthomas / chroma,A general purpose syntax highlighter in pure Go,160,"[Go, Python]"
23,arendst / Tasmota,Alternative firmware for ESP8266 with easy con...,No details available,"[C, C++, HTML, Berry, Python, Makefile]"
24,nvm-sh / nvm,Node Version Manager - POSIX-compliant bash sc...,No details available,"[Shell, Makefile]"

Q6. Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [2]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(2)

In [3]:
#clicking the hot 100 songs link
charts=driver.find_element_by_xpath("//ul[@class='o-nav__list lrv-a-unstyle-list lrv-u-flex lrv-u-justify-content-center lrv-a-space-children-horizontal a-space-children--60@custom lrv-u-justify-content-space-evenly@desktop lrv-u-font-size-15 u-letter-spacing-0043 a-font-primary-medium-s u-display-none@mobile-max']/li[1]/a")
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(2)

In [4]:
#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[1]/h3[1]")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(2)    


#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[1]/span")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('No details available')
time.sleep(2)
    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[4]/span")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(2)

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[5]/span")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(2)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//ul[@class='lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max']/li[6]/span")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,As It Was,Harry Styles,1,1,11
1,First Class,Jack Harlow,2,1,10
2,Wait For U,Future Featuring Drake & Tems,3,1,7
3,About Damn Time,Lizzo,5,4,9
4,Running Up That Hill (A Deal With God),Kate Bush,4,4,23
...,...,...,...,...,...
95,Plan B,Megan Thee Stallion,95,29,4
96,Tomorrow Me,Luke Combs,-,61,2
97,Potion,"Calvin Harris, Dua Lipa & Young Thug",87,71,3
98,New Truck,Dylan Scott,-,99,1
99,Wrapped Around Your Finger,Post Malone,47,47,2

Q7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [33]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the naukri.com
url = "https://www.naukri.com/"
driver.get(url)
time.sleep(2)

In [38]:
#clicking on search button
skill=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[1]/div/div/div/input")
skill.click()
time.sleep(2)

#accesing search bar
search=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[1]/div/div/div/input")
search.send_keys("Data Science")
time.sleep(2)

#clicking on search button
button=driver.find_element_by_xpath("/html/body/div/div[2]/div[3]/div/div/div[6]")
button.click()
time.sleep(2)

In [43]:
#clicking on recruiters link
recruiters=driver.find_element_by_xpath("//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

#accesing search bar
search=driver.find_element_by_xpath("//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

#clicking on search button
button=driver.find_element_by_xpath("//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

In [47]:
#scrapping names
name=[]
try:
    names=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a/span[1]")
    for i in names:
        name.append(i.text)
except NoSuchElementException:           #handling no such element exception
    name.append('No details available')
time.sleep(2)


#scrapping designation
designation=[]
try:
    designation_list=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/span[1]")
    for i in designation_list:
        designation.append(i.text)
except NoSuchElementException:        #handling no such element exception
    designation.append('No details available')
time.sleep(2)


#scrapping company names
company=[]
try:
    companies=driver.find_elements_by_xpath("//div[@class='recInfo']/div/p/a[2]")
    for i in companies:
        company.append(i.text)
except NoSuchElementException:#handling no such element exception
    company.append('No details available')
time.sleep(2)

#scrapping location names
location=[]
soup=BeautifulSoup(driver.page_source,'html.parser')
l=soup.find_all('div',attrs={'vcard'})
for i in l:
    try:
        location.append(i.find('small').text)
    except AttributeError :
        location.append("No details available")
time.sleep(2)

#skills they hire for
skill=[]
try:
    skills=driver.find_elements_by_xpath("//div[@class='recInfo']/div[2]")
    for i in skills:
        skill.append(i.text)
except NoSuchElementException:        #handling no such element exception
    skill.append('No details available')
time.sleep(2) 

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Designation':designation,
                'Company':company,
                "Location":location,
                'Skills I hire':skill})
df

,Name,Designation,Company,Location,Skills I hire
0,Aakash Harit,HR Manager,Data Science Network,Delhi,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,Hyderabad / Secunderabad,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Pune,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,Ahmedabad,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,UK - (london),"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Vadodara / Baroda,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Chennai,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Trivandrum,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Indore,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Bengaluru / Bangalore,"Software Development, It Sales, Account Manage..."
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Hyderabad,"Oracle Dba, Data Science, Data Warehousing, ET..."
11,Kalpana Dumpala,Executive Hiring,Innominds Software,Hyderabad / Secunderabad,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
12,Mubarak,Company HR,MoneyTap,Bengaluru / Bangalore,"Business Intelligence, Data Warehousing, Data ..."
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,Mumbai,"Office Administration, Hr Administration, tele..."
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Hyderabad / Secunderabad,"Social Media, digital media maketing, seo, smm..."
15,Kapil Devang,HR Manager,BISP Solutions,Bhopal,"Big Data, Hadoop, Data Analytics, Data Science"
16,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Chandigarh,"React.js, Data Science, Java, Front End, Busin..."
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Pune,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
18,Manisha Yadav,HR Executive,Easi Tax,Navi Mumbai,"Telecalling, Client Interaction, Marketing, Re..."
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Cochin,Data Science
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Delhi,"Corporate Sales, Software Development, Softwar..."
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,Hyderabad / Secunderabad,"Data Analytics, Data Science, Machine Learning..."
22,Rithika dadwal,HR Recruiter,Affine Analytics,Pune,"Data Science, Machine Learning, Python, R, Dee..."
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Pune,"Big Data, Data Science, Artificial Intelligenc..."
24,Shaun Rao,Manager Human Resources,Exela Technologies,Pune,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Pune,"Data Science, Artificial Intelligence, Machine..."
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,Bengaluru / Bangalore,"Software Architecture, Vp Engineering, Product..."
27,kumar,Proprietor,trainin,Bengaluru / Bangalore,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,No details available,"Signal Processing, Machine Learning, Neural Ne..."
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Delhi,"Web Technologies, Project Management, Software..."
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Bengaluru / Bangalore,"Server Administartion, Verilog, Vhdl, Digital ..."
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Mysoru / Mysore,"Data Analytics, Managed Services, Team Leading..."
32,Avodha,Business Development Associate,Nikitha Palaparthi,Hyderabad / Secunderabad,"Ethical Hacking, Security Operations Center, S..."
33,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,Hyderabad / Secunderabad,"Data Science, Machine Learning, Big Data Analy..."
34,Priya Khare,Senior Manager,Independent Consultant,Bengaluru / Bangalore,"Data Science, Artificial Intelligence, analyti..."
35,Amit Sharma,Consultant,ASCO consulting,New Delhi,"Machine Learning, Artificial Intelligence, Dat..."
36,Kanan,senior technology instructor,NY INST,Chennai,"C, C++, Artificial Intelligence, Python, Php, ..."
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Aligarh,"Relationship Management, Retail Sales, Private..."
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Salt Lake City,"Data Science, Software Engineering"
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Pune,"Data Science, Big Data Analytics, Digital Mark..."
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Bengaluru / Bangalore,"Data Science, Recruitment, Salary"
41,Ankit Sinha,Head Analytics,Suntech Global,Mumbai,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Indore,"Software Development, Business Intelligence, B..."
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Bengaluru / Bangalore,"Data Science, Node.js, Angularjs"
44,Ashwini,Director Global Delivery,MRP Advisers,MYSORE,"Data Science, Media Marketing, Resource Planni..."
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Hyderabad / Secunderabad,"Data Analysis, Learning, Data Science, Compute..."
46,Rajani Nagaraj,HR Manager,WildJasmine,Bengaluru / Bangalore,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
47,ROHIT Kumar,Architect,LNT Private Limited,Mumbai,"Software Development, Core Java, Unit Testing,..."
48,Amir Chowdhury,Managing Partner,Granular.ai,No details available,"Machine Learning, Data Science, Product Manage..."
49,Ravi Dubey,Recruitment Manager,HyrEzy Talent Solutions LLP,Ghaziabad,Walmart Interra Skeps Expressstores indifi whi...

Q8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [48]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the theguardian.com
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"
driver.get(url)
time.sleep(2)

In [49]:
#scrapping book names
book_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[2]")
    for i in names:
        book_name.append(i.text)
except NoSuchElementException:              #handling no such element exception
    book_name.append('No details available')
time.sleep(2)

#scrapping author names
author_name=[]
try:
    names=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[3]")
    for i in names:
        author_name.append(i.text)
except NoSuchElementException:#handling no such element exception
    author_name.append('No details available')
time.sleep(2)


#scrapping Sale
Sale=[]
try:
    sale=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[4]")
    for i in sale:
        Sale.append(i.text)
except NoSuchElementException:#handling no such element exception
    Sale.append('No details available')
time.sleep(2)    

#scrapping publisher
publisher=[]
try:
    publishers=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[5]")
    for i in publishers:
        publisher.append(i.text)
except NoSuchElementException:#handling no such element exception
    publisher.append('No details available')
time.sleep(2)

#scrapping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//table[@class='in-article sortable']/tbody/tr/td[6]")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)

#creating dataframe
df=pd.DataFrame({"Book_name":book_name,
                "Author_name":author_name,
                'Volume sold':Sale,
                'Publisher':publisher,
                'Genre':genre})
df

,Book_name,Author_name,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

Q9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [50]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://www.imdb.com/list/ls095964455"
driver.get(url)
time.sleep(2)

In [51]:
# scraping name of webseries
name=[]
try:
    names=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
    for i in names:
        name.append(i.text)
except NosuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)


# scraping year of release
years=[]
try:
    span=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/span[2]")
    for i in span:
        years.append(i.text)
except NosuchElementException:#handling no such element exception
    years.append('No details available')
time.sleep(2)


# scraping genre
genre=[]
try:
    genres=driver.find_elements_by_xpath("//span[@class='genre']")
    for i in genres:
        genre.append(i.text)
except NoSuchElementException:#handling no such element exception
    genre.append('No details available')
time.sleep(2)


# scraping run_time
run_time=[]
try:
    info=driver.find_elements_by_xpath("//span[@class='runtime']")
    for i in info:
        run_time.append(i.text)
except NoSuchElementException:#handling no such element exception
    run_time.append('No details available')
time.sleep(2)


# scraping rating
rating=[]
try:
    info=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]")
    for i in info:
        rating.append(i.text)
except NoSuchElementException:#handling no such element exception
    rating.append('No details available')
time.sleep(2)

# scraping votes
votes=[]
try:
    info=driver.find_elements_by_xpath("//span[@name='nv']")
    for i in info:
        votes.append(i.text)
except NoSuchElementException:#handling no such element exception
    votes.append('No details available')
time.sleep(2)


#creating dataframe
df=pd.DataFrame({"Name":name,
                "years":years,
                "Genre":genre,
                "Run_time":run_time,
                "Rating":rating,
                "Votes":votes})
df

,Name,years,Genre,Run_time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,998,308"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,046,257"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"950,935"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"284,210"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"244,002"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.4,"48,938"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"59,648"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"190,886"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,377"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"229,410"

Q10. Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code

In [52]:
# Activating the chrome browser
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(2)

# Opening the imdb.com
url = "https://archive.ics.uci.edu/"
driver.get(url)
time.sleep(2)

In [53]:
#clicking show all datasets link
show=driver.find_element_by_xpath("//a[@href='datasets.php']")
show.click()
time.sleep(1)

In [55]:
#scraping dataset names
name=[]
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping dataset datatype
data_type=[]
try:
    datatypes=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in datatypes[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset default task
default_task=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in info[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset attribute type
attr_type=[]
try:
    attr_types=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attr_types[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset no. of instance
no_of_instances=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in info[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset no. of attributes
no_of_attributes=[]
try:
    info=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in info[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset year
year=[]
try:
    years=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in years[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021